# version: '3'
# services:
#   db:
#     image: mysql/mysql-server:latest
#     container_name: mysql
#     restart: always
#     environment:
#       # MYSQL_ROOT_USER: root
#       MYSQL_ROOT_PASSWORD: root
#       # MYSQL_DATABASE: test_db
#       MYSQL_ROOT_HOST: 'localhost' 
#     ports:
#       - "3306:3306"
#     # volumes:
#     #   - data:/var/lib/mysql
#     #   -  "./mysql:/var/lib/mysql"
#     #   -  "./mysql/my.cnf:/etc/mysql/my.cnf"

#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin:latest
#     container_name: phpmyadmin
#     restart: always
#     environment:
#       PMA_HOST: localhost
#       # PMA_USER: root
#       # PMA_PASSWORD: password
#       # PMA_ARBITRARY: 1
      
#     ports:
#       - "8080:80"
#     # volumes:
#     #   - ./config.inc.php:/etc/phpmyadmin/config.inc.php

# volumes:
#   data:

version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      # MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 'password'
      # MYSQL_DATABASE: test_db
      # MYSQL_ROOT_HOST: 'localhost' 
    ports:
      - "3306:3306"
    # volumes:
    #   - data:/var/lib/mysql
    #   -  "./mysql:/var/lib/mysql"
    #   -  "./mysql/my.cnf:/etc/mysql/my.cnf"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: 'db' 
      # PMA_USER: root
      # PMA_PASSWORD: password
      # PMA_ARBITRARY: 1
      
    ports:
      - "8080:80"
    # volumes:
    #   - ./config.inc.php:/etc/phpmyadmin/config.inc.php

#volumes:
 # data: