FROM postgres:latest

RUN apt-get update && apt-get install -y --no-install-recommends \
    postgresql-13-postgis-3 \
    postgresql-13-postgis-3-scripts \
    postgresql-13-pgrouting \
    && rm -rf /var/lib/apt/lists/*

ENV POSTGRES_USER=postgres \
    POSTGRES_PASSWORD=password \
    POSTGRES_DB=mydb

ADD ./init.sql /docker-entrypoint-initdb.d/
